package com.edunetcracker.simulator.model;

import com.edunetcracker.simulator.service.status.SequenceStatus;

public interface DBObject<T> {
    /**
     * <B>CONSIDER BEFORE USING!!</B>
     * Copies all necessary references from <i>another</i> object, for
     * this being able to operate as the <i>another</i>.
     *
     * @param another Object which references to copy.
     * @return A rate of success.
     */
    SequenceStatus copyRefs (T another);

    /**
     * <B>SAFE TO USE</B>
     * Copies all <i>another's</i> autogenerated by SQL fields, for this to
     * become a just-as-equal representation of a database row
     * as the <i>another</i>.
     *
     * @param another Object which autogenerated fields to copy
     * @return A rate of success.
     */
    SequenceStatus copyAutogeneratedValues (T another);
}
